### ISSUE TITLE
Category Pages Styling

### ISSUE THREAD

**Issue by gdpittman** [MattSLangford/Tiny-Theme-for-Micro.blog#5]
Hi, Matt. The Archive pages seem to have inconsistent CSS for metadata than other pages in the theme. The first screenshot below is from my category page and the second is from your site. Your site is what I would expect. [You see my example live here.](https://gregorypittman.net/categories/humor/) Looks like the theme's version uses `<span class="post-meta"...` as a separate tag and your version uses `class="post-date u-url` inside the `<a href>` tag.

![CleanShot 2023-06-25 at 19 56 29@2x](https://github.com/MattSLangford/Tiny-Theme-for-Micro.blog/assets/75804019/e20635e6-677d-448c-aeac-0cc9fe31b5fc)
![CleanShot 2023-06-25 at 19 56 47@2x](https://github.com/MattSLangford/Tiny-Theme-for-Micro.blog/assets/75804019/305a99a1-647b-4320-9994-956eb0302daf)

**Comment by gdpittman** [comment]
Fixed with CSS

Update: Actually, I was able to fix the metadata styles but on pages with titles, the metadata comes after the title. Titles, however, are tagged with `<h1>` instead of `<h2>`. ~~I would create a custom theme and fix this myself but I can't seem to locate the correct file.~~ I found the file, forked the theme. All fixed on my end. Sorry for the trouble!

**Comment by MattSLangford** [comment]
Thanks for the heads up. Wasn't visible in other places due to a plugin conflict. Everything has been resolved.
