### ISSUE TITLE
Mistyped font stack name

### ISSUE THREAD

**Issue by edoardob90** [MattSLangford/Tiny-Theme-for-Micro.blog#8]
I guess it should be `--font_monospace_slab_serif` here:

https://github.com/MattSLangford/Tiny-Theme-for-Micro.blog/blob/40eb256515439eaeee578ecf5e7a2983ba4cc556/static/css/main.css#L44

Not a big deal, it's indeed a _tiny_ issue 😉  Thanks for your work with this theme!

**Comment by MattSLangford** [comment]
Oh, good catch. Fixed and pushed out the update in 1.8.14. Thanks.
